<?php

$lang = array(

	'other' => 'อื่น ๆ',
	'app_connent_ok' => 'เชื่อมต่อได้',
	'app_connent_false' => 'เชื่อมต่อไม่ได้',

	'note_deleteuser' => 'ลบสมาชิก',
	'note_renameuser' => 'เปลี่ยนชื่อสมาชิก',
	'note_deletefriend' => 'ลบเพื่อน',
	'note_gettag' => 'คำค้น TAG',
	'note_getcreditsettings' => 'ตั้งค่าคะแนน',
	'note_updatecreditsettings' => 'อัปเดตการตั้งค่าคะแนน',
	'note_updateclient' => 'อัปเดตแคชแอพลิเคชัน',
	'note_updatepw' => 'อัปเดตรหัสผ่านของสมาชิก',
	'note_updatebadwords' => 'อัปเดตรายการตัวกรองคำ',
	'note_updatehosts' => 'อัปเดตชื่อโดเมน',
	'note_updateapps' => 'อัปเดตแอพลิเคชัน',
	'note_updatetagtemplate' => 'อัปเดตคำค้นและเทมเพลท',
	'note_list' => 'รายการการแจ้งเตือน',
	'note_test' => 'ทดสอบ',
	'note_delete' => 'ลบ',
	'note_succeed' => 'แจ้งเตือนเมื่อประสบความสำเร็จ',
	'note_na' => 'ไม่มีการแจ้งเตือน',
	'note_false' => 'แจ้งเตือนเมื่อประสบล้มเหลว',
	'note_times' => 'เวลา',

	'pm_from' => 'จาก',
	'pm_to' => 'ส่งให้',
	'pm_system' => 'ข้อความจากระบบ',
	'pm_date' => 'เวลา',
	'pm_daterange_1' => 'วันนี้',
	'pm_daterange_2' => 'เมื่อวาน',
	'pm_daterange_3' => 'เมื่อวานซืน',
	'pm_daterange_4' => 'สัปดาห์ที่แล้ว',
	'pm_daterange_5' => 'ก่อนหน้านี้',
	'pm_notitle' => '[ไม่มีหัวข้อ]',

	'user_add' => 'เพิ่มสมาชิก',
	'user_delete' => 'ลบสมาชิก',
	'login' => 'เข้าสู่ระบบ',
	'logout' => 'ออกจากระบบ',
	'app_add' => 'เพิ่มแอพลิเคชัน',
	'app_delete' => 'แอพลิเคชัน',
	'app_edit' => 'แก้ไขแอพลิเคชัน',
	'setting_update' => 'อัปเดตการตั้งค่าพื้นฐาน',
	'setting_register_update' => 'อัปเดตการตั้งค่าการสมัครสมาชิก',
	'pm_send' => 'ส่งข้อความสาธารณะ',
	'pm_delete' => 'ลบข้อความสาธารณะ',
	'pm_clear' => 'เคลียร์ข้อความ',
	'badword_add' => 'เพิ่มตัวกรองคำ',
	'badword_delete' => 'ลบตัวกรองคำ',
	'admin_add' => 'เพิ่มผู้ดูแลระบบ',
	'admin_pw_edit' => 'แก้ไขรหัสผ่านผู้ดูแลระบบ',
	'admin_priv_edit' => 'แก้ไขสิทธิ์ผู้ดูแลระบบ',
	'domain_add' => 'เพิ่มชื่อโดเมน',
	'domain_delete' => 'ลบชื่อโดเมน',
	'credit_addexchange' => 'เพิ่มโครงการแลกเปลี่ยนคะแนน',
	'credit_deleteexchange' => 'ลบโครงการแลกเปลี่ยนคะแนน',
	'credit_sync' => 'การตั้งค่าคะแนนของแอพพลิเคชั่นพร้อมกัน',
	'db_export' => 'สำรองข้อมูล',
	'db_import' => 'นำเข้าข้อมูล',
	'db_delete' => 'ลบข้อมูล',
	'note_delete' => 'ลบเรียบร้อย',
	'note_send' => 'ส่งใหม่',
	'dumpfile_exists' => 'มีการสำรองข้อมูล',
	'dumpfile_not_exists' => 'ไม่มีการสำรองข้อมูล',
);